# Generated by Django 3.2.6 on 2023-07-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='size',
            field=models.IntegerField(default=20),
        ),
    ]
