# Generated by Django 3.2.6 on 2023-07-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='partner',
            field=models.CharField(default='Gemal', max_length=100),
        ),
    ]
