# Generated by Django 3.2.6 on 2023-07-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_container_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='invoice',
        ),
        migrations.AddField(
            model_name='container',
            name='invoice',
            field=models.ManyToManyField(related_name='containers', to='home.Invoice'),
        ),
    ]
