# Generated by Django 3.2.6 on 2023-07-05 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
