# Generated by Django 3.2.6 on 2023-07-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230709_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='price',
            field=models.IntegerField(default=20),
        ),
    ]
