# Generated by Django 3.2.6 on 2023-07-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customer_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='id_invoice',
            field=models.CharField(default='00000000', max_length=20),
        ),
    ]
