# Generated by Django 3.2.6 on 2023-07-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_invoice_id_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id_invoice',
            field=models.CharField(default='00000000', max_length=100),
        ),
    ]
