# Generated by Django 3.2.6 on 2023-07-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_invoice_id_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_cbm',
        ),
    ]
