# Generated by Django 3.2.6 on 2023-07-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_container_manifaist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
