# Generated by Django 3.2.6 on 2023-07-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_container_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='Unpaid', max_length=100),
        ),
    ]
