# Generated by Django 3.2.6 on 2023-08-03 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_customertransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeInvoice',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Unpaid', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeinvoices', to='home.customer')),
            ],
        ),
    ]
