# Generated by Django 3.2.6 on 2023-08-05 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230805_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freetransaction',
            old_name='paid',
            new_name='rest',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='paid',
            new_name='rest',
        ),
    ]
